SELECT DISTINCT ?city ?cityLabel ?location ?locode WHERE {
  { ?city (wdt:P31/wdt:P279*) wd:Q515. } UNION { ?city (wdt:P31/wdt:P279*) wd:Q15284. }
  ?city wdt:P17 wd:Q183.
  ?city wdt:P625 ?location.
  OPTIONAL { ?city wdt:P1937 ?locode. }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
}
ORDER BY ?cityLabel
